# Indices of Abundance

Given Rougheye/Blackspotted are associated with deep, structured habitats, it can be difficult to survey them. Four general fishery-independent bottom trawl surveys were used in the 2013 assessment, and are again included in this assessment:

* Triennial (every three years) survey (1980-2004)
* Alaska Fishery Science Center Slope survey (1997-2001)
* Northwest Fisheries Science Center Slope Center (1999-2001)
* West Coast Groundfish Bottom Trawl Survey (WCGBTS; 2003-2204)

Only the WCGBTS has new data for this assessment, but new methods (Spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/)) to develop an index of abundance were applied to all surveys to update all indices. Two distributions (gamma and lognormal) were considered, as was the case in 2013 model when a non-spatial generalized linear mixed model was used to develop indices of abundance.

WCBGTS:

The data were truncated to depths less than 875 m prior to modelling given that there were zero positive encounters in depths deeper than 875 m. The prediction grid was also truncated to only include available survey locations in depths between 55-875 m to limit extrapolating beyond the data and edge effects. 

The response variable in the model was catch (mt) with an offset of area (km2) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariate was included: pass. 

Spatial variation, but not spatiotemporal variation, was included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 200 knots, where more knots led to non-estimable standard errors because the positive encounters are too sparse to support the dense spatiotemporal structure.


## Additional Items for Discussion


