# Introduction

This document presents the stock assessment for the Rougheye (*Sebastes aleutianus*) and Blackspotted (*Sebastes melanostictus*) rockfishes, two species that form one management complex. This report is for the year 2025 in state and federal waters from California to Washington State, excluding consideration of the Puget Sound and Salish Sea (@fig-map). It seeks to use available catch, biological compositions in the for of lengths and ages, and potential indices of abundance and is the first assessment since the 2013 stock assessment [@hicks_status_2013].



## Choice of Stock Structure

There are at least two questions to think about when considering stock structure for Rougheye and Blackspotted rockfishes when doing a stock assessment.

1.  Rougheye and Blackspotted rockfishes are two different species– can we separate them as two stocks and conduct separate assessments? 
Rougheye rockfish were first described in 1811 as *Perca variabilis* by German zoologist Peter Simon Pallas [@jordan_fishes_1898], and assigned to various taxa at least 15 times since [@love_rockfishes_2002]. Some descriptions noted both light and dark color morphs, which, along with possible confusion with several morphologically similar co-occurring species (e.g., *S. borealis* and *S. melanostomus*) have contributed to the persistent ambiguity in formal descriptions of Rougheye Rockfish [@orr_species_2008]. The first genetic studies conducted in the late 1960s and early 1970s [@tsuyuki_contribution_1968; @tsuyuki_analyses_1970] observed diversity suggestive of two genetic types within specimens identified as Rougheye Rockfish. Allozyme studies conducted over the next two decades [@seeb_biochemical_1986; @hawkins_genetic_1997; @hawkins_genetic_2005] provided additional evidence suggesting two separate genetic types within field-identified Rougheye Rockfish.  Genetic variation between the two types, supported by both nuclear and mitochondrial DNA, was determined to be sufficiently conclusive to separate two species: “Type I” and “Type II” Rougheye Rockfish [@gharrett_two_2005]. Meristic and morphometric comparisons of the two species suggested certain characters such as gill raker counts and length, snout length, anal base length, and pectoral fin base were significantly different, and in combination could reliably, though not definitively, distinguish between the species[@gharrett_genetically_2006].  The two separate species were formally re-described by @orr_species_2008 with the Type II group retaining *S. aleutianus* and the common name Rougheye Rockfish.  Blackspotted rockfish was proposed as the common name for the Type I group along with the scientific name of *S. melanostictus*, re-establishing nomenclature from one of the species complex’s earlier descriptions [@matsubara_1934].

These two species remain difficult to consistently differentiate visually in the catch, thus are still commonly reported and treated as a species complex. Otolith morphometrics (e.g., shape, size, weight) have shown some promise in possibly identifying these species in Alaskan waters (97.3% Blackspotted and 86.2% of Rougheye rockfishes were accurately identified) and possibly using older otoliths to break out historical information by species [@harris_using_2019]. Frey et al. (in prep.) provided insight into the ability of the Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey biologists to identify the two species, with 90% of genetically identified Rougheye rockfish being correctly identified in the field. When mis-identifications occurred, it was usually a Blackspotted rockfish being mis-identified as a Rougheye rockfish. There were few mis-identifications when a fish was identified as a Blackspotted rockfish. While this is promising for potential future species-specific data coming from the survey, it does not alleviate the historical problem of separating fishery data into the two species. Frey et al. (in prep.) therefore also considered whether ecological factors like depth or latitude could help separate samples by species. They found that both species occur within the range of this assessment’s considered areas (California to Washington), and heavily spatially overlap. Interestingly, there seem to be relative hot spots for these species where one species is more common than the other, and in general, Rougheye rockfish seems to be more common than Blackspotted rockfish (however, Blackspotted rockfish may be the more common of the two in parts of Alaska; @gharrett_two_2005; @hawkins_genetic_2005; @orr_species_2008). Overall, there seems to be little ability to separate current or historical fishery data reliably in order to separate these two species into two stocks, so we will maintain a species complex approach, though given absolute presence off the U.S. West coast, this may be considered more of a Rougheye than Blackspotted stock assessment. We also note that throughout the range of these stocks, all current assessments to this point have maintained a species complex approach.

Despite some identification advances and Rougheye and Blackspotted rockfishes are clearly genetically distinct species, data historically and contemporaneously remain available only for the Rougheye/Blackspotted Rockfish complex, not at the species level.  While we treat these species as one assessed stock complex, we recognize and are mindful of the above species distinctions as we conduct our analyses.

2. Both species range into Canada and Alaska– are they one stock? 
While genetics studies have focused mostly on identification of the two species, little is known about the population structure of either species. This assessment and the 2013 assessment [@hicks_status_2013] represent the most southerly range of these species. Comparing the absolute abundance of the 2013 assessment to the most current estimates of the Alaskan stocks, the absolute number in this southerly range is much smaller than in the Gulf of Alaska (GOA), but higher than in the Bering Sea/Aleutian Island (BSAI) stock (@fig-SO_comp). The two smaller stocks have similar trend of decline and stabilization, whereas the higher biomass GOA stock looks to have not dropped at all over the time period considered (@fig-RSS_comp). We assume here that the west coast stocks of Rougheye/Blackspotted rockfishes are distinct management units from those in Alaska.

## Distribution 
`R Spp` range from northern California up to and throughout Alaska and into Japan [@gharrett_two_2005; @hawkins_genetic_2005; @orr_species_2008]. Both are long-lived (>100 years), with Rougheye Rockfish having the distinction of the oldest ever aged *Sebastes* species at 205 years old. They both greatly overlap in latitude and depth (shallower than 100 m to at least 439 m), and are generally considered slope rockfish, with an ontogenetic shift from shallower to deeper, and adults commonly found at 360 m (around 200 fathoms). Rougheye seems to be proportionally more abundant when survey samples are genetically identified, and Blackspotted Rockfish tend to be found, on average, deeper than Rougheye Rockfish [@hawkins_genetic_2005; @orr_species_2008]. 

`R Spp` are often associated with structure, such as hard, rocky bottoms and steep habitats. They are rarely found on the deep flats. They can be found alone or in aggregations [@love_rockfishes_2002], with aggregations often differentiated by age.  Younger fish may school and are often found in shallower waters on the shelf, junveiles and subadults can be found together, and larger fish may form larger aggregations in the Pacific Northwest during the autumn and winter. These two species may also hybridize on occasion [@love_certainly_2011]. These species are closely related to Shortraker Rockfish (*S. borealis*) and are sometimes difficult to distinguish from Shortraker Rockfish without looking at the gill rakers. One major distinguishing feature of Rougheye Rockfish are the 2–10 spines along the lower rim of their eyes, hence the common name "rougheye".

## A Map Showing the Scope of the Assessment

## Important features of life history

Like all *Sebastes* species, Rougheye and Blackspotted Rockfishes give birth to live young. Larvae released has been documented between February and June and extrusion lengths are between 4.5-5.3 mm [@love_rockfishes_2002]. There are no studies on the fecundity of rougheye rockfish on the west coast of the U.S.

A wide range of prey items make up the diet of rougheye rockfish.  Crangid and pandalid shrimps make up the majority of their diets, and larger individuals, greater than 30 cm, feeding upon other fishes [@love_certainly_2011].  They are also known to feed upon gammarid amphipods; mysids, crabs, polychaetes, and octopuses [@love_rockfishes_2002; @love_certainly_2011].


## Ecosystem Considerations



## Historical and Current Fishery Information
`R Spp` are not often targeted by a specific fishery, but are desirable and marketable, thus are typically retained when captured.  They are often captured in bottom trawl, mid-water trawl, and longline fisheries.  Small numbers have been observed in pot, shrimp, and recreational fisheries.

After many attempts to start trawl fisheries off the west coast of the United States in the late 1800’s, the availability of the otter trawl and the diesel engine in the mid-1920’s helped the trawl fisheries expand [@douglas_species_1998]. The trawl fisheries really became established during World War II when demand increased for shark livers and bottomfish. A mink food fishery also developed during World War II [@jones_oregon_1961], and post-war catches for rockfishes, including `r Spp`, increased [@niska_species_1976]. Foreign fleets began fishing for rockfish in the mid 1960’s until the EEZ was implemented in 1977 [@rogers_species_2003].  Since 1977, landings of rockfish were high until management restrictions were implemented in 2000.  Longline catches of rougheye rockfish are present from the turn of the century and continue in recent years, targeting sablefish and halibut.  The catches by state for the trawl and hook & line fleets as well as for the Pacific whiting at-sea fleet are shown in ******.

A long-term directed fishery has not occurred for rougheye rockfish and historical discarding practices are not well known.  Rougheye rockfish inhabit deeper water as adults, which were fished less often historically.  More detailed information of the fisheries by state is given in Section ******* where the reconstructed landings are discussed.

## Summary of Management History 
`r spp` has been a small component of groundfish fisheries and catches of `r Spp` have been governed by restrictions on assemblages of species, of which these species are a member. However, the distribution of fishing effort in areas where `r Spp` might be encountered has also been affected by catch restrictions on co-occurring, rebuilding species, as well as associated area closures instituted to promote rebuilding. The first imposed landings limits on a coastwide Sebastes complex (`r Spp` being one of the 50 rockfishes in the complex) were instituted in 1983. Ongoing concern that shelf and slope rockfishes may be undergoing overfishing led the attempt by @rogers_status_1996 to describe the status of most rockfishes contained in the Sebastes complex. `r Spp` information content was low, and using the Triennial survey to calculate an average biomass and assuming that fishing mortality equals natural mortality provided estimates of exploitation rates that indicated the stock was undergoing very high exploitation rates in both management areas. The dividing line between the northern and southern management areas was shifted to 40º 10’ N latitude in 1999 and the Sebastes complex was subsequently divided into nearshore, shelf, and slope complexes in 2000. `r Spp` has been managed under trip limits for the minor slope rockfish complex in both north and south management areas since this time. 

## Management Performance
Table @management-summary summarizes major management changes since 2000. Some important changes include the implementation of Rockfish Conservation Areas (RCA’s) in 2002, the beginning of trawl rationalization in 2011, and the lifting of the RCAs beginning in 2020 with the removal of the trawl RCA in Oregon and California and loosening restrictions in the non-trawl RCAs in 2023 and 2024.

Though managed as part of a complex, OFL contributions for `r spp` were calculated using DB-SRA in 2010 for the 2011-2012 management cycle. This lead to the observation that recent catches had frequently exceeded the OFL contribution estimated using data-poor, catch-only methods provided a strong indication that a more thorough evaluation of `r Spp` stock status and sustainable harvest levels be undertaken, using all available data. A full assessment of `r spp` was undertaken in 2013 and indicated the stock complex was above management target levels (@hicks_status_2013). Recent management performance for `r spp` as a part of the nothern minor slope rockfish complex is provided in Table @managment-performance (ALI IS STILL CREATING THIS TABLE - WILL ADD TEXT FOR IT LATER).

<!-- Management performance, including a table or tables comparing Overfishing Limit (OFL), Acceptable Biological Catch (ABC), Annual Catch Limit (ACL), landings, and catch (i.e., landings plus discard) for each area and year. Groundfish assessments that estimate dead discarded catch must include a disclaimer noting that total mortality estimates from the WCGOP and from the stock assessment may differ due to the use of different methods. Investigation into how these methods differ is beyond the scope of a benchmark assessment. The rationale for modeling discard mortality can also be provided. This should be included in all update assessments.  -->


## Fisheries off Canada and Alaska

`R spp` are distributed throughout Canada and Alaska and are commonly caught in trawl and hook & line fisheries.  Alaska conducts assessments biennially for the Rougheye/Blackspotted complex, and two have been recently done: one for the Bering Sea and Aluetian Islands [@spencer_assessment_2023] and the other for the Gulf of Alaska [@sullivan_assessment_2023]. Canada completed an assessment in 2020 [@starr_rougheyeblackspotted_2020].  The fisheries and assessments for each country are described below.

Rougheye rockfish have been managed as a bycatch only species in Alaska since 1991 with catches ranging between 130 and 2,418 mt and peaking in the late 1980s and early 1990s [@sullivan_assessment_2023]. Generally, about 55-75% of the catch are trawl-caught and 30-45% from hook-and-line (mainly, longline) fisheries. Since 2017 the move to pot gear in the sablefish fishery has decreased the longline catches. Discards since 2013 have ranged from 11.6% (in 2023) and 45% (in 2018). The Rougheye/Blackspotted complex catch levels generally are between 20% and 60% of the Total Allowable Catch since the 2005 when the complex began to be managed separately. The most recent age-structured integrated stock assessments of this complex in the Bering Sea and Aluetian Islands [@spencer_assessment_2023] and for the Gulf of Alaska [@sullivan_assessment_2023] do not indicate either overfishing or the stocks being overfished.

Canada identified two species of rougheye rockfish (Type I and Type II) in 2007 and designated both species of special concern, which means that they may become threatened or endangered because of a combination of biological characteristics and identified threats [@cosewic_2007]. This designation was given because biomass estimates are uncertain and no strong trends are observed, there is evidence of truncation of the age distribution and overall mortality has doubled, it is a long-lived, low-fecundity Sebastes species, which is susceptible to population collapse and slow recovery, and because the difficulty in separating the two species may result in potential impacts on one of the species going unnoticed. Subsequently, the species were identified as rougheye rockfish and blackspotted rockfish and a management plan was created in 2012 with a goal of sustaining the populations of rougheye and blackspotted rockfishes [@fisheries_and_oceans_canada_management_2012]. Five high priority and seven low priority actions have been identified to address the threats to the populations and support the management goal. 

The first Canadian stock assessment for these species, using a integrated catch-at-age model, was conducted in 2022 to estimated stock status of two Rougheye/Blackspotted (REBS) rockfishes management units (REBS north and REBS south) a the beginning of 2021. The REBS north stock was in the healthy zone in the reference model. The REBS south stock was likely in the healthy zone, but with an elevated possibility of being in the cautious zone. 



