# Data

Data from a wide range of sources were evaluated within this assessment. Data sources included in the assessment model are summarized in @fig-data. Description of each data source used in the model is provided below.

<!--- Provide temporal and spatial resolutions or sample size where appropriate for each of the subsections, below.--->

## Fishery-dependent data

<!-- Commercial fisheries landings by state, year, and gear (PacFIN is the standard source for recent domestic commercial landings), historical catch estimates, discards, recreational fisheries catches, foreign removals; sample size information for length- and age-composition data by state, year and gear, including both the number of trips and fish sampled. Description of methods to estimate abundance indices, sample size information by survey and year. Include complete tables and figures and date of data extraction. -->
`r Spp` are not targeted by a specific fishery, but are desirable and marketable, thus are typically retained when captured. They are often captured in bottom trawl, mid-water trawl, and longline fisheries. Small numbers have been observed in pot and shrimp trawl. Recreational catch is inconsequential and not accounted for in this assessment. 

Fishery depended data for `r Spp` in this assessment are divided among six fleets, which include:

* Fleet 1: Commercial trawl fishery
* Fleet 2: Dead discard trawl
* Fleet 3: Commercial fixed gear (mainly the long-line) fishery 
* Fleet 4: Dead discard non-trawl
* Fleet 5: Contemporary mid-water fishery
* Fleet 6: At-sea hake fishery

For description and details on fleet structure, please refer to Section \ref{Fleet and Survey Designations}. 

### Commercial Fishery Landings
Recent and historical fisheries landings were compiled by state and then combined into the fishing fleets used in the assessment. Time series of landings by fleet and state are reported in Table  X. Time series of fisheries catches by fleet are shown in @fig-landings.

#### Recent landings
Recent commercial landings of `r Spp` (2000-2024 for Washington, 1987–2024 for Oregon and 1981–2024 for California,) were obtained from PacFIN, a regional fisheries database that manages fishery-dependent information in cooperation with West Coast state agencies and National Marine Fisheries 
Service (NMFS). Catch data were extracted from PacFIN on April 24, 2025. 

#### Historical Landings
Historical landings of `r Spp` were reconstructed by state, by year (Table X). 

The Washington historical landings (1889–2000) of `r Spp` were provided by Washington Department of Fish and Wildlife (WDFW), who recently conducted historical catch reconstruction for rockfish species including `r Spp` (pers. comm. T. Tsou, WDFW). The three main sources used in this reconstruction  included the US Fish Commission Report (UFSC), Washington Bound Volumes, and Washington Statistical Bulletin (SpeciesSumOutput2_2017.csv- ADD TABLE). The historical species composition was based on the various historical reports and interviews of fishermen and dockside samplers. The 1981 to 2000 landings are provided by WDFW as well (rather than obtaibed from PacFIN), since those landings are derived by WDFW via a improved method for apportioning out unidentified rockfish (URCK) category in fish tickets to the species level. This improved approach relaxed the borrowing rules for missing data used in the WDFW species allocation algorithm that feeds into PacFIN (pers. comm. T. Tsou, WDFW). New Washington historical landings represent improvement to the assessment. 

The Oregon historical landings (1896–1986) were obtained from Oregon historical catch reconstruction, conducted by Oregon Department of Fish and Wildlife (ODFW) in collaboration with NWFSC (@karnowski_historical_2014). 
The Oregon landings for the period between 1987 and 1999 were also provided by the ODFW. For that peios, Oregon PacFIN landings were supplemented with the additional estimates of `r Spp`landings reported within unspecified rockfish market categories,  (i.e., URCK and POP1; @ODFW_URCK_POP_recon). 

The California historical landings were informed by several sources. Landings from the most recent “historical” period (between 1969 and 1980) were obtaned from the California Cooperative Survey (CalCOM) database. Earlier landing records (between 1931 and 1968) were informed by the rockfish historical catch reconstruction conducted by the NOAA's Southwest Fisheries Science Center (@ralston_documentation_2010). 

Comparison of `r Spp` historical landings by state and fleet between this and 2013 assessment is provided in @fig-Ct_All. 
The largest differences in this assessment from 2013 model are in Washington landings (@fig-Ct_WA), with newly estimated landings being generally lower than those used in previous assessment.  The new WDFW catch reconstruction completed by WDFW is considered an improvement.  

Historical California and Oregon landings did not change substantially (@fig-Ct_CA and @fig-Ct_OR), with the exception of a few years. Discrepancies in California and Oregon non-trawl landings between the 2013 and 2025 assessments are caused by the fact that non-trawl fleet in 2013 assessment was limited to only fixed gear, when in 2025 assessment non-trawl fleet includes all non-trawl gear groups.  Slight discrepancies in Oregon trawl landings between 1987 and 1999, are from adding previously non-reported landings of `r Spp` in the unspecified rockfish market categories (see details above). 

The update in historical changes shows only minor differences in model outputs (@fig-Ct_compsSO; @fig-Ct_compsRSS).

#### Bycatch in the foreign POP fishery
Between mid-1960s and mid-1970s, foreign trawl fleets from the former Soviet Union, Japan, Poland, Bulgaria and East Germany targeted aggregations of Pacific ocean perch in the Northeast Pacific Ocean, in the waters off the U.S. West Coast (Love et al., 2002). Rogers (2003) estimated removals of rockfish species caught within this foreign POP fishery, including removals of `r Spp`. In the assessment, `r Spp` bycatch in the foreign POP fishery between 1966 and 1976 as estimated by Rogers (2003) were added to commercial bottom trawl fleet.

#### At-Sea Hake Catches
`r Spp` has long been bycaught in the fishery for the coastal population of Pacific hake, which is almost exclusively conducted with mid-water trawls. 

Large-scale harvesting of Pacific hake in the United States began in late-1960s, when factory trawlers from the Soviet Union and other countries began targeting this stock. After the 200-mile U.S. Exclusive Economic Zone was declared in 1977, a Joint-Venture fishery was initiated between United States trawlers and Soviet factory trawlers acting as mother-ships (larger, slower ships for fish processing and storage while at sea). By 1989 the U.S. fleet capacity had grown to a level sufficient to harvest the entire quota, and no further foreign fishing was allowed. The Pacific hake fishery is currently 100% observed by the at-sea hake observer program (A-SHOP) and data on bycatch species, including `r Spp`, is being routinely collected. 

Annual amounts of `r Spp` bycatch (retained and discarded) in the Pacific hake fishery were obtained from the North Pacific Database Program (NORPAC). That time series covers the period between 1977 and 2024 and include catches by foreign and domestic fisheries as well as removals during the time of Joint Ventures (JV). `r Spp` catches within the at-sea hake fishery were treated in the model as a separate fleet.

### Discards

#### Historical discard
Historically, little to no discarding was observed for `r Spp`. 

The historical discard information comes from Pikitch et al. (1988), and often referred to as the Pikitch study. The Pikitch study was conducted between 1985 and 1987 between 48°42’ and 42°60’ N. latitude, which is primarily within the Columbia INPFC area (Pikitch et al. 1988). Participation in the study was voluntary and included vessels using bottom, midwater and shrimp trawl gears. Observers of normal fishing operations on commercial vessels collected the data, estimated the total weight of the catch by tow, and recorded the weight of species retained and discarded in the sample. 

There are no midwater trawl records of `r Spp`in the Pikitch study, and only few fish records of bottom trawl catches, based on which  discard rate (discard weight over total weight) for bottom trawl was just 0.09%. Therefore, no historical discard was assumed in the model.

#### Recent Discard
With the introduction of trip limits for rockfish in early 2000, limited discard has been observed for `r Spp`in bottom trawl and non-trawl fisheries. 

In 2002, the West Coast Groundfish Observer Program (WCGOP) was implemented on the West Coast of the United States, which began with gathering bycatch and discard information for the limited entry trawl and fixed gear fleets. Observer coverage has expanded to include the California halibut trawl, the nearshore fixed gear and pink shrimp trawl fisheries. Since 2011, trawl fisheries have been managed with catch shares under a system of annual individual fishing quotas (IFQs) for the shoreside sector (i.e., vessels delivering to shoreside processors) and harvest cooperatives for the at-sea hake sectors (catcher-processors who catch and process hake at sea; and Motherships, factory processors that take delivery of hake from catcher vessels at sea). Constant monitoring of catch using observers or electronic monitoring (EM) is required to participate in the trawl catch share fishery. 

The discard amounts of `r Spp` for the period between 2002 and 2023 were obtained from WCGOP by year and fleet (bottom trawl, mid-water trawl and non-trawl), for both the catch share and the non-catch share sector. The discarding amounts of `r Spp` within bottom trawl and non-trawl fleets were included in the model as separate fleets. 

Mid-water trawl discard was not present in non-catch share sector and was extremely minimal (virtually non-existing) in catch-share sector, with discard amounts averaging to 10kg per year. Therefore, in the model, no discard was assumed for mid-water trawl fleet. 

##### Bottom Trawl Discard
Bottom trawl discard amounts by year are provided in Table XX. Prior to 2011, before the start of the catch share program, the discard of `r Spp` ranged between 1 metric ton and 60 metric tons, averaging at 23 metric tons a year. After 2011, the discard has been very low, not exceeding 0.5 metric ton a year. No discard data were available for 2024, and we used the average discard amount for 2019 - 2023 period to approximate 2024 discards for bottom trawl discard fleet.

##### Non-Trawl Discard
Non-trawl discard amounts by year are provided in Table XX. Non-trawl discard of `r Spp` were made in both catch share and non-catch share sectors. Discard amounts in these sectors were combined by year to represent total discard within the fleet. The discards within this fleet ranged between 0.5 metric ton and 35 metric tons, with 10 metric tons as average per year. No discard data were available for 2024, and the 2023 discard amount was assumed for 2024 for non-trawl discard fleet.

### Fishery Length and Age Data
Length bins from 10 to 80 cm in 2 cm increments were used to summarize the length frequency of the catches in each year. The first length bin includes all observations less than 10 cm and the last bin includes all fish 80 cm and longer. Age distributions included bins from age 1 to age 100, with the first bin including all fish ages 0 and 1 and the last bin including all fish age 100 and above.

#### Commercial Landings Length and Ages
The fishery length and age data for bottom trawl, non-trawl and midwater trawl fleets, based on samples collected by port samplers, were obtained from the PacFIN Biological Data System (BDS) database and extracted on April 24, 2025. The number of trips and fish sampled for lengths and ages by fleet and year are summarized in Tables XX-XX. 

Commercial length-frequency distributions were developed for each fleet and year, for which observations were available (Figire. Females and males distributions were treated separately, to track sex-specific differences. For each fleet, the raw observations were expanded to the trip level, to account for differences in samples sizes relative catch weights among trips (first stage expansion). The expanded length observations were then further expanded to state level, to account for differences in sampling intensity of `r Spp` landings among states combined into a single fleet (second stage expansion). The expansion algorithm can be illustrated with the following equation:

\begin{centering}

$N_{b,j,y} = \displaystyle\sum_{s=1}^{s=k}\displaystyle\sum_{t=1}^{t=n}L_{b,j,t} \cdot
\left(\frac{LC_t}{SC_t}\right) \cdot \left(\frac{LC_{s,y}}{SC_{s,y}}\right)$

\end{centering}

Where $N_{b,j,y}$ is the number of lengths in each length bin ($b$) by sex ($j$) and year ($y$) within each fleet. $L_{b,j,t}$ represents an individual length sample by bin ($b$) and sex ($j$) within an individual fishing trip ($t$). In the first stage expansion, $L_{b,j,t}$ was multiplied by the ratio of landed catch ($LC_t$) within that trip ($t$) to a portion of catch sampled for lengths ($SC_t$) within the same trip ($t$). In the second stage expansion, the individual length sample ($L_{b,j,t}$) was multiplied by the ratio of landed catch ($LC_{s,y}$) within individual state ($s$) and year ($y$) to catch weights sampled for lengths ($SC_{s,y}$) within the same state ($s$) and year ($y$). As the final step, the expanded length samples from the same size bin and sex were summed across all trips and states (combined into a single fleet) within a single year, to obtain the total number of lengths in each length bin by sex, year and fleet ($N_{b,j,y}$). The same calculations were repeated for each length bin, to develop sex specific length frequencies for each fishing fleet by year. 

Age distributions were included in the model as conditional-age-at-length (CAAL) observations. The marginal age-compositions were also included, but only for evaluating the implied fits, while the CAAL data were used in the likelihood. The CAAL data were not expanded and were binned according to length, age, sex, and year.

The filtering and processing of the PacFIN length and age composition data were conducted using the pacfintools package in R (Wetzel et al. 2025). The filtering steps included removing samples with missing vital information. Figures XX show the commercial length and age frequencies used in the model for each fleet.

The initial input values for length compositions in this assessment were calculated as a function of the number of trips and number of fish via the Stewart Method (pers.comm. I. Stewart, International Pacific Halibut Commission (IPHC)). The method is based on analysis of the input and model derived effective sample sizes from West Coast groundfish stock assessments. A piece-wise linear regression was used to estimate the increase in effective sample size per sample based on fish-per-sample and the maximum effective sample size for large numbers of individual fish. The resulting equations are:

\begin{centering}

Input effN = $N_{\text{trips}} + 0.138 * N_{\text{fish}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $<$ 44

Input effN = $7.06 * N_{\text{trips}}$ if $N_{\text{fish}}/N_{\text{trips}}$ is $\geq$ 44

\end{centering}

The input sample size of CAAL data was set at the number of fish at each length by sex and by year. 

##### Commercial Discard Lengths
Discard length composition data for both bottom trawl and non-trawl discard fleets were available from WCGOP. Discard length composition data were not sex-specific. Discard raw legnth observations were expanded to the haul level, to account for differences in catch among hauls. 

The initial input values for length compositions were calculated via the Stewart Method (see above). 

No age data were available for discarded fish.

##### At-sea hake Fishery Length and Age Compositions
The sex-specific length and age data for at-sea hake fleet were collected by the at-sea hake observer program (a-shop) and available through NORPAC database. Input sample sizes for length compositions were based on the number of hauls sampled by year. 

Age distributions were included in the model as CAAL observations, binned according to length, age, sex, and year. The input sample size of CAAL data was set at the number of fish at each length by sex and by year. 

The marginal age compositions were constructed, but only used in the model for evaluating the implied fits, while the CAAL data were used in the likelihood.

## Fishery-independent data

<!-- Fishery-independent data: Description of surveys used in the assessment, description of methods to estimate abundance indices, sample size information for length- and age- composition data by survey and year, including both the number of tows (or drops or sites for hook and line data) and fish sampled. Include complete tables and figures and date of data extraction.   -->

Data from four fishery-independent surveys were used in this assessment: 

* AFSC/NWFSC West Coast Triennial (every three years) Shelf survey (1980-2004)
* Alaska Fishery Science Center Slope survey (1997, 1999-2001)
* Northwest Fisheries Science Center Slope Center (1999-2002)
* West Coast Groundfish Bottom Trawl Survey (WCGBTS; 2003-2024)

Information produced by these surveys included indices of relative abundance (all four surveys), length-frequency distributions (Triennial survey and WCGBTS), and age-frequency distributions (WCGBTS). 

Only the WCGBTS has new data for this assessment, but new methods were applied to all surveys to develop new indices of abundance. We used geostatistical models of biomass density to fit to survey data using spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/). The method is based on a delta model. Two distributions (gamma and lognormal) were considered for the catch-rate component, but the lognormal error structure was selected for all surveys because it was shown to be able to better account for extreme catch events. Comparing the standardized versions (i.e., Z-scores, which puts all the indices on the same scale for better comparison of trends)  shows very similar trends among each model output in the indices, suggesting little difference in choice of model type. The variance in the indices is generally high (0.3-0.5), suggesting the information content in these indices is low, which is consistent with the known challenge of sampling these species with trawl gear. Overall, catches densities are highest in northern Oregon and Washington. 

Description of each survey is provided below; information available from each survey and methods used to process the data are also discussed.  

### AFSC/NWFSC West Coast Triennial Shelf Survey
#### Survey Description

The triennial survey was first conducted by the AFSC in 1977 and spanned the time frame from 1977–
2004. The survey’s design and sampling methods are most recently described in **Weinberg et al. (2002)**.
Its basic design was a series of equally-spaced transects from which searches for tows in a specific depth
range were initiated **(Figure X)**. The survey spatial coverage and timing has changed over the period of survey duration **(Table X,
Figure X)**. 

Haul depths ranged from 91–457 m during the 1977 survey with no hauls shallower than 91 m. The
surveys in 1980, 1983, and 1986 covered the West Coast south to 36.8°N latitude and a depth range of
55–366 meters. The surveys in 1989 and 1992 covered the same depth range but extended the southern
range to 34.5°N (near Point Conception). From 1995 through 2004, the surveys covered the consistent depth range
55–500 meters and surveyed south to 34.5°N. In the final year of the triennial series (2004), the
NWFSC conducted the survey and followed very similar protocols as the AFSC, which conducted surveys in all previous years.

All of the surveys were conducted in the mid-summer through early fall: the 1977
survey was conducted from early July through late September; the surveys from 1980 through 1989 ran
from mid-July to late September; the 1992 survey spanned from mid-July through early October; the 1995
survey was conducted from early June to late August; the 1998 survey ran from early June through early
August; and the 2001 and 2004 surveys were conducted in May-July **(Figure X)**.

Given the different depths surveyed during 1977, the data from that year were not included in this
assessment. Water hauls **(Zimmermann et al. 2003)** and tows located in Canadian waters were also
excluded from the analysis of this survey. 

#### Abundance Index
Geostatistical models of biomass density were fit to survey data using spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/). The model used a delta model with a lognormal distribution for the catch-rate component.

A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km$^2$) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariates were included: pass. Vessel-year effects, which have traditionally been included in index standardization for this survey, were not included as the estimated variance for the random effect was close to zero. Vessel-year effects were more prominent when models did not include spatial effects and were included for each unique combination of vessel and year in the data to account for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014].

Spatial and spatiotemporal variation was included in the encounter probability and the positive catch rate model.
Spatial variation was approximated using 200 knots, where more knots led to non-estimable standard errors because the positive encounters are too sparse to support the dense spatiotemporal structure.

In this assessment, the survey was analyzed as an early series (1980–1992) and a late series (1995–2004) to account for change in spatial coverage and survey timing, as has been done in many other West Coast rockfish assessments. Separate catchability parameters estimated for pre-1995 period and from 1995 forward. Separate selectivity curves were estimated for early and late survey periods. 

<!-- NEED TO UPDATE THIS: The indices for the early and late series of this survey were estimated separately using a GLMM with the
stratifications shown in **Table X**. Boxplots of the deviance for the late and early triennial survey series are
shown in **Figure X** and show that the lognormal distribution had the lowest median deviance for both
series. Random or fixed strata-year effects produced similar deviance, and the random strata-year effects
were chosen as the final models. Selection of using the extreme catch event mixture distribution (ECE)
was done by investigating the Q-Q plots in **Figure X**. The Q-Q plot for no ECE does not show any
departures from the assumed distribution, and the ECE Q-Q plot did not show improvement. Therefore,
the lognormal distribution without the ECE mixture distribution and random effects on the year-strata
interaction were used to estimate the indices shown in **Figure X** and **Table X**. The early series suggests a
possible slightly increasing trend in biomass from 1983–1992, while the late series showed no discernible
trend and alternated between high and low estimates from 1995–2004. The design-based estimates
(average density expanded to the stratum area then summed over strata) are compared to the model-based estimates in **Figure X**. 
Similar trends are seen for both sets of estimates, but the design-based estimates
are consistently greater than the model-based estimates by more than a factor of 2. This suggests that the
scale of the model-based estimates may be low, which may be caused by incorrect expansion to the
proper area. This is not an issue with the assessment because a catchability coefficient relating the survey
biomass to the assessment model biomass is estimated without any prior assumption on what value that
catchability coefficient should be. Therefore, caution is advised if attempting to interpret the value of that
estimated catchability coefficient. -->

#### Length Compositions
Length bins from 10 to 80 cm in 2 cm increments were used to summarize the length frequency of the survey catches in each year (Figure XX). Table XX shows the number of lengths taken by the survey. 

Length compositions were separated into males and females. These length compositions were expanded to account for difference in catch among tows, with further expansion based upon the stratification by depth and latitude using the {nwfscSurvey} package in R [@wetzel_nwfscsurvey_2023]. The stratification for length data expansions are provided in Table XX.

The input sample sizes for length composition data for all fishery-independent surveys were calculated based on Stewart and Hamel [-@stewart_bootstrapping_2014] as $\text{Input N}_{y} = 2.43*N_{tow}$ where the 2.43 value was estimated for a group of shelf and slope rockfish species.

There are no `r spp` age data from the Triennial Survey.

### AFSC Slope Survey

#### Survey Description
The AFSC slope survey was initiated in 1984. The survey methods are described in Lauth (2000). Prior to 1997, the survey was conducted in different latitudinal ranges each year (Table 5). In this assessment, only data from 1997, 1999, 2000 and 2001 were used – these years were consistent in latitudinal range (from 34°30’ N. latitude to the U.S.-Canada border) and depth coverage (183-1280 m; 100-700 fm).

#### Abundance Index
Geostatistical models of biomass density were fit to survey data using spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/). The model used a delta model with a lognormal distribution for the catch-rate component. 

The data were truncated to depths less than 875 m prior to modelling given that there were zero positive encounters in depths deeper than 875 m. The prediction grid was also truncated to only include available survey locations in depths between 55-875 m to limit extrapolating beyond the data and edge effects. The response variable in the model was catch (mt) with an offset of area (km2) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariate was included: pass. Spatial variation, but not spatiotemporal variation, was included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 200 knots, where more knots led to non-estimable standard errors.

#### Length Compositions
Length bins from 10 to 80 cm in 2 cm increments were used to summarize the length frequency of the survey catches in each year (Figure XX). Table XX shows the number of lengths taken by the survey. 

Length compositions were separated into males and females. These length compositions were expanded to account for difference in catch among tows, with further expansion based upon the stratification by depth and latitude using the {nwfscSurvey} package in R [@wetzel_nwfscsurvey_2023]. The stratification for length data expansions are provided in Table XX.

The input sample sizes for length composition data for all fishery-independent surveys were calculated based on Stewart and Hamel [-@stewart_bootstrapping_2014] as $\text{Input N}_{y} = 2.43*N_{tow}$ where the 2.43 value was estimated for a group of shelf and slope rockfish species.

There are no `r spp` age data from the AFSC Slope Survey.

### NWFSC Slope Survey

#### Survey Description
The NWFSC slope survey was conducted annually from 1999 to 2002. The survey’s design and sampling methods are described in Keller et al.(2007). The surveyed area ranged between 34°50’ and 48°07’ N. latitude, encompassing the U.S. Vancouver, Columbia, Eureka, Monterey INPFC areas, and a portion of the Conception area, and consistently covered depths from 100 to 700 fm (183-1280 m) (Table XX).

#### Abundance Index
Geostatistical models of biomass density were fit to survey data using spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/). The model used a delta model with a lognormal distribution for the catch-rate component.

The data were truncated to depths less than 875 m prior to modelling given that there were zero positive encounters in depths deeper than 875 m. The prediction grid was also truncated to only include available survey locations in depths between 55-875 m to limit extrapolating beyond the data and edge effects. 

The response variable in the model was catch (mt) with an offset of area (km2) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariate was included: pass. Spatial variation, but not spatiotemporal variation, was included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 200 knots, where more knots led to non-estimable standard errors.

There are no `r spp` length and age data from the NWFSC Slope Survey. Given that spatial coverage of NWFSC Slope Survey is the same of AFSC Slope Survey, selectivity of the NWFSC SLope Survey was assumed the same as selectivity of AFSC Slope Survey (mirrored in the model).   

### NWFSC West Coast Groundfish Bottom Trawl Survey

#### Survey Description
The West Coast Groundfish Bottom Trawl Survey (WCGBTS) is conducted annually since 2003 (Table XX). The survey’s design and sampling methods are most recently described in @bradburn_2003_2011. The survey is based on a random-grid design, covering the coastal waters from a depth of 100 to 700 fm (183-1280 m). This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

#### Abundance Index
Geostatistical models of biomass density were fit to survey data using spatial and spatiotemporal GLMMs with TMB or [sdmTMB](https://pbs-assess.github.io/sdmTMB/)[@kristensen_tmb:_2016] via the R package \gls{sdmtmb} [@Anderson:2022:SRP].. The model used a delta model with a lognormal distribution for the catch-rate component.

The data were truncated to depths less than 875 m prior to modelling given that there were zero positive encounters in depths deeper than 875 m. The prediction grid was also truncated to only include available survey locations in depths between 55-875 m to limit extrapolating beyond the data and edge effects. 

The response variable in the model was catch (mt) with an offset of area (km2) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariate was included: pass. Spatial variation, but not spatiotemporal variation, was included in the encounter probability and the positive catch rate model. Spatial variation was approximated using 200 knots, where more knots led to non-estimable standard errors.

The data were truncated to depths less than 675 m prior to modeling given that there were zero positive encounters in depths deeper than 675 m. The prediction grid was also truncated to only include available survey locations in depths between 55-875 m to limit extrapolating beyond the data and edge effects.

The model used a delta model with a lognormal distribution for the catch-rate component. The model used a delta model with a lognormal distribution for the catch-rate component. A logit-link was used for encounter probability and a log-link for positive catch rates. The response variable was catch (mt) with an offset of area (km$^2$) to account for differences in effort. Fixed effects were estimated for each year. The following additional covariates were included: pass. Vessel-year effects, which have traditionally been included in index standardization for this survey, were not included as the estimated variance for the random effect was close to zero. Vessel-year effects were more prominent when models did not include spatial effects and were included for each unique combination of vessel and year in the data to account for the random selection of commercial vessels used during sampling [@helser_generalized_2004; @thorson_accounting_2014].

Spatial and spatiotemporal variation was included in the encounter probability and the positive catch rate model.
Spatial variation was approximated using 500 knots, where more knots led to non-estimable standard errors because the positive encounters are too sparse to support the dense spatiotemporal structure.

The estimated distribution of `r spp` density for 2004 is shown in Figure \ref{fig:survey-density}.

#### Length and Age compositions
Length bins from 1o to 80 cm in 2 cm increments were used to summarize the length frequency of the survey catches in each year (Figure XX). Table XX shows the number of lengths taken by the survey. 

Length compositions were separated into males and females. These length compositions were expanded to account for difference in catch among tows, with further expansion based upon the stratification by depth and latitude using the {nwfscSurvey} package in R [@wetzel_nwfscsurvey_2023]. The stratification for length data expansions are provided in Table XX.

The input sample sizes for length composition data were calculated based on Stewart and Hamel [-@stewart_bootstrapping_2014] as $\text{Input N}_{y} = 2.43*N_{tow}$ where the 2.43 value was estimated for a group of shelf and slope rockfish species.

Age distributions included bins from age 1 to age 100, with the last bin including all fish of greater age. Table XX shows the number of ages taken by the survey. Age distributions were included in the model as CAAL observations. The marginal age compositions were only used for comparing the implied fits, while the CAAL data were used in the likelihood. The CAAL data were not expanded and were binned according to length, age, sex, and year.

The input sample size of CAAL data was set at the number of fish at each length by sex and by year. 

## Biological Parameters
The major biological inputs to the models are natural mortality, age and growth parameters, weight-length, maturity and stock-recruitment parameters. The following sections outline the treatment of each section. One change from the previous assessment is moving to a two sex from the one-sex specification from 2013. The 2013 stock assessment one-sex specification was based on the observation that the biology of females and males was very similar, thus justifying the simplifying assumption of one sex. The following sections below demonstrates that females and males do generally have similar growth, though there are differences, but may have different natural mortality values. The current assessment will use a two sex configuration that allows for flexibility to set female and male parameters either equal (i.e., functionally equivalent to a one sex model) and or sex-specific. @fig-Sex1vs2_SO and @fig-Sex1vs2_Bratio show that using a two sex configuration with the same life history parameters for females and males is equivalent to the one sex model. Note that the one sex model sums up both female and male biomass, thus why it is twice the size as the two sex female-only spawning output (@fig-Sex1vs2_Bratio).

### Natural Mortality
Natural mortality is a highly influential parameter in age-structured stock assessments. It defines the rate of natural death by age, and thus establishes a stable age-structure and expectation of longevity, and interacts with growth and reproduction to determine stock productivity. It is a very difficult parameter to directly measure, thus empirical relationships based on life history parameters are often used to indirectly determine its value or build prior distributions in belief of what it is in the event we do attempt to estimate it in the model (@cope_upgrading_2022; @hamel_development_2022; @maunder_review_2023). If length and age data are available, it may be possible to estimate it in the model.

An estimate of maximum age tends to be the most reliable life history parameter related to natural mortality to inform its estimation. @cope_upgrading_2022 ([The Natural Mortality Tool](https://connect.fisheries.noaa.gov/natural-mortality-tool/)) provide the most up-to-date examination of the relationship between maximum age and natural mortality

\begin{centering}

$M=\frac{5.4}{A_{\text{max}}}$

\end{centering}

\vspace{0.5cm}

where $M$ is natural mortality and ${A_{\text{max}}}$ is the assumed maximum age. The prior is defined as a lognormal distribution with mean $ln(5.4/A_{\text{max}})$ and standard error = 0.31. This is the equation typically used to estimate a natural mortality point estimate, but is underpinned by the choice of the value of ${A_{\text{max}}}$. This equation assumes that the proportion of the stable population at this maximum age is 0.4517%. If we take humans as an example, the longest lived human is 122 years. This is not the maximum age, but the oldest ever recorded age. The maximum age that corresponds to 0.4517% of the population is around 100 years. For Rougheye/Blackspotted, the oldest ever aged individual is 205 years with unknown ageing error. We did not consider this as a realistic maximum age.

The 2013 U.S. west coast stock assessment used a prior built around a mean of 0.034 (corresponding to a maximum age of 163), but estimated natural mortality at 0.042 (maximum age between 128-129 years; Figure M). The 2023 Gulf of Alaska assessment built a prior conditional on a estimate of natural mortality from their 5 oldest aged individuals that ranged from 126-135 years. This resulted in a mean value of 0.042, similar to the 2013 U.S. west coast stock assessment. The 2023 Bering Sea/Aleutian Islands assessment used M = 0.05 (assumed longevity of 108), and the recent Canadian assessments considered a range of M values from 0.03 to 0.055 (assumed maximum ages of 180 to 98 years; @fig-Mcurves). 

We attempt to estimate natural mortality, as was done in the 2013 U.S. West coast assessment. Examining the available age data, the oldest 10 individuals range from 139 to 165 and were all males. For females, the 10 oldest individuals range from 130 to 121 years. If those oldest ages were used in the @hamel_development_2022 longevity estimator, these ages would correspond to a range of natural mortality values of 0.033 to 0.039 for males, which include the mean of the prior used in the 2013 assessment. For females, it corresponds to natural mortality values of 0.039 to 0.045. All these assume that the sampled population has enough of an age structure still available for sampling, as opposed to having some level of age truncation from the theoretical unfished stable age distribution.  

Related to this issue of possible age truncation, applying a catch curve analysis (taking the log of the abundance of numbers of samples in available age classes) on the aggregated ages across all age sources by sex, the total mortality (Natural + Fishing mortality= Total mortality) is 0.046 for females and 0.035 for males, which may indicate the natural mortality could be lower than that used in the 2013 assessment, but within the range of values considered in other areas (@fig-CC_Z). This also indicates the possibility of estimating sex-specific natural mortality, as natural mortality may differ by sex. The two sex model allows for this type of model specification exploration. Further exploration was done my truncating the upper ages considered, with the assumption that the older ages may also not be sampled fully (i.e., dome-shaped selectivity). We considered both 100 (@fig-CC_Z_100) and 80 (@fig-CC_Z_80) as upper age cut-offs. The less older individuals included, the higher the estimate of total mortality, and this a higher natural mortality. But we can see a general overestimate of how many older individuals are expected using these higher Z values, thus dome-shapeness does not see to explain the sampling of these older individuals.

One challenge to estimating natural mortality within the model is the interaction of estimating dome-shaped selectivity with estimating natural mortality. If all fleets assume some level of dome-shaped selectivity, it is difficult to determine if the unseen larger, older individuals are due to natural death or fishing mortality. Typically, at least one major fleet needs to achieve full selectivity for the larger, older individuals. The 2013 assessment suggested some dome-shaped selectivity in the two major fleets, thus any natural mortality estimates are evaluated depending on the forms of fleet selectivity.


### Growth (Length-at-Age)
Age and length data are used to estimate important growth parameters. @fig-AL_1 has the currently available age and length data. Female and male sample sizes are very similar. Estimated growth curves are also presented in @fig-AL_1 and the parameters are provided in Table AL_1. The West Coast Groundfish Bottom Trawl Survey clearly and importantly samples the smallest, youngest individuals compared to the other two data sources. This allows for a better estimate of the age at size 0 (t~0~) and growth coefficient (k). The female asymptotic size (L~$\infty$~) is estimated notably higher from the PacFIN data, though male estimates of Linf are similar across the data sets. The overall externally derived estimates of female and male `r Spp` are

\begin{centering}

Females $L_{\infty}$ = 59.03 cm; $k$ = 0.07; $t_0$ = -2.45

Males $L_{\infty}$ = 56.69 cm; $k$ = 0.08; $t_0$ = -2.03

\end{centering}

The coefficient of variation (CV) of length by age and sex are shown in @fig-AL_2. This is a measure of the variation in length for a given age class. Sample sizes are highest from the youngest ages up to around 70 (females) to 80 (males) years. The smoothed line shows the average response, and indicates similar CVs values for females and males, with the highest at the youngest ages, but generally 0.1. The amount and range of age samples, along with repeated length samples within an age class, allows growth parameters (L~$\infty$~, k, t~0~, and CVs at age) to be estimated in the model. Ages are conditioned on lengths in the model in order to estimate growth within the model. We also explore sensitivity in growth values by pre-specifying growth to different values.

We note that the growth values being estimated in our data are notably different than those used in Alaska. For instance, the growth parameters for the BSAI stock is L~$\infty$~ = 51.43, k = 0.06 and t~0~ = -3.30 and L~$\infty$~ = 54.2 cm, k = 0.07, t~0~= -1.5 for the GOA population (both sexes combined). These growth parameters shows a larger size and faster growth of the West Coast stock complex versus those in Alaska, though the West Coast stock complex is more similar to the GOA complex.

### Ageing Bias and Precision
Counting ages from ageing structures in long-lived, temperate fishes is challenging. Ages derived from these structures can be hard to reproduce within and between readers (i.e., imprecision), and may not contain the true age (i.e., bias). Stock assessment outputs can be affected by bias and imprecision in ageing, thus it is important to quantify and integrate this source of variability when fitting age data in assessments. In Stock Synthesis 3, this is done by including ageing error matrices that include the mean age (row 1) and standard deviation in age (row 2). Ageing bias is implemented when the inputted mean age deviates from the expected middle age for any given age bin (e.g., 1.75 inputted versus 1.5 being the true age for the age 1 bin); ageing imprecision is given as the standard deviation for each age bin.

There are eight primary readers that provided the available ages, two of which often split the ageing duties. @fig-AE_matrices shows which reader assignments are given to each year of ages by data source. Reader 7 is the mix of two readers that shared reading duties within years.  

Estimation of ageing error matrices used the approach of -@punt_quantifying_2008 in two different forms: one developed in AD Model Builder (\href{https://github.com/pfmc-assessments/nwfscAgeingError}{nwfscAgeingError} [@thorson_nwfscageingerror:_2012]) and one adapted to Template Model Builder framework (\href{https://pfmc-assessments.github.io/AgeingError/articles/getting_started.html}{TMB}). The ageing error matrix offers a way to calculate both bias and imprecision in age reads. Reader 1 is always considered unbiased, but may be imprecise. Bias relative to the primary reader is given for the second reader. There were three age readers that were assumed to be unbiased. In those cases, 12 model configurations based on different assumptions of imprecision (constant CV, curvilinear standard deviation, or curvilinear CV, along with an option to either share or independently estimate imprecision between readers) were considered. For the other four age readers that could be biased and/or imprecise, thirty-six total model configurations were explored that included the above imprecision models as well as an exploration of the functional form of bias (e.g., no bias, constant coefficient of variation, or non-linear bias) in the second reader. 

Model selection criteria included AIC corrected for small sample size (AICc), which converges to AIC when sample sizes are large, and Bayesian Information Criterion (BIC). Both ADMB and TMB were run using an (\href{https://github.com/shcaba/Ageing_Error_app}{ageing error shiny app}). Model selection was then compared between ADMB and TMB, which did not always agree, so model selection criteria was added across the two modeling approaches to get an overall model selection criteria. Ageing error matrices were also inspected for behavior in the best supported models to make sure outrageously large precision or bias was not chosen (effectively rendering the ages worthless, which is not an assumption of the quality of the ages). @fig-AE_bias and @fig-AE_SD show the bias and imprecision assumptions applied for each ageing error (AE) matrix.


### Length-Weight Relationship
Female and male length-weight relationships were determined using data from the PacFIN database, West Coast Groundfish Bottom Trawl Survey, and ASHOP samples. Samples size by sex were: female (N=13839), males (13625), and unknown sex (53). Each of the data sources estimated very similar length-weight relationships (@fig-LW1).

The resultant sex-specific length-weight relationships are given in @fig-LW2, with the following individual values: 

* Females: W = 0.000008L^3.15
* Males: W = 0.000012L^3.07

These values are very similar to the previous assessment that used a combine sex value of a=0.0000096 and b=3.12000 (@fig-LW2).

### Maturity

Maturity for the Rougheye/Blackspotted Rockfish complex was estimated using 473 maturity samples collected from 2015 to 2024 on gls\{odfw} and gls\{wdfw} surveys and the gls\{indexwc} in California, Oregon, and Washington waters (M. Head, pers. comm.). The samples included 194 samples genetically assigned as Rougheye Rockfish, 71 samples genetically assigned as Blackspotted Rockfish, and 208 samples with no genetic assignment. The maturity schedule was assumed to be length-based, as in the 2013 benchmark assessment. This assessment used the functional classification of maturity to describe the maturity schedule, which not only identifies the individuals that are physiologically capable of producing yolk (those that are biologically mature), but also accounts for the occurrence of abortive maturation and skipped spawning, so the functional maturity classification is a more accurate representation of the individuals that may actually spawn in a given year. This is a difference from the 2013 benchmark assessment, which did not explicitly estimate functional maturity, and instead assumed the biological classification of maturity.

Biological maturity and functional maturity observations were fitted in separate models. Biological maturity and functional maturity status observations (0 = immature and 1 = mature) were fitted in a logistic regression model (glm R function, family = binomial, link = “logit”). The estimated model parameters were used to calculate length at 50% maturity (L50%; **Table XXX table Melissa provided**) and maturity ogives (**Fig. XXX figure Melissa provided, the one comparing biological and functional maturity**). The delta method was used to calculate 95% confidence intervals of L50% estimates. The estimated L50% (functional maturity; L50%fxn) was 46.53 cm and the estimated slope of the maturity oogive was 0.25. Sensitivities were run using the estimate of biological maturity and the maturity estimate used in the 2013 benchmark assessment. There was little evidence of skipped spawning, so we did not explore fitting the data with a spline model.

Because there are known life history differences between Rougheye Rockfish and Blackspotted Rockfish, maturity was also estimated for each species, using the samples that were genetically assigned to each species, respectively, using the same methods as above (**Table XXX table Melissa provided and Figure XXX figure Melissa provided, the one comparing overall functional maturity at length and for the two species**). Two sensitivities were run using the functional maturity L50% (and slope) estimated for 1) Rougheye Rockfish and 2) Blackspotted Rockfish (which mature at larger sizes on average than Rougheye Rockfish).

Sensitivities were run using functional age at 50% maturity estimate for the species complex (n = 372) and for each species separately. Age at 50% maturity was estimated using the same methods as for length at 50% maturity (**Table XXX table Melissa provided and Figure XXX figure Melissa provided, the one comparing overall functional maturity at age and for the two species**).

### Fecundity
The 2013 U.S. west coast stock assessment assumed that fecundity was proportional to weight. Dick et al. (2017) provided a study on rockfishes showing that rockfishes routinely have a non-proportional relationship of fecundity to weight, with larger individuals producing more eggs than expected only by weight. Neither Rougheye or Blackspotted rockfishes have a species- of subfamily-specific estimate for this relationship, so this stock assessment uses the unobserved Genus Sebastes values of a = 6.538e-06 and b = 4.043 using the F=aL^b relationship.

### Stock-Recruitment Function and Compensation
The Beverton-Holt stock recruit relationship is assumed, as it was in the 2013 assessment, to describe the relationship between spawning biomass and recruitment. The steepness parameter may be considered for estimation, but it is notoriously difficult to estimate in assessment models. The 2013 stock assessment used the previous rockfish steepness mean value of 0.77, but this has subsequently been updated to 0.72, to a value that represents a stock with somewhat lower recruitment compensation. Natural variation in recruitment (i.e., not deterministically taken from the stock-recruit curve) is apparent in the length and age data (as notable length or age classes growing/ageing over time), so deviations in recruitment are estimated.

### Sex Ratio
No information on the sex ratio at birth was available so it was assumed to be 50:50. 

## Environmental and ecosystem data
This stock assessment does not explicitly incorporate trophic interactions, habitat factors or environmental factors into the assessment model. More predation, diet and habitat work, and mechanistic linkages to environmental conditions would be needed to incorporate these elements into the stock assessment and should remain a priority. @McClure:2023:VCC report the climate vulnerability for several west coast groundfishes, including `r spp`. `r Spp` demonstrated both high biological sensitivity and high climate exposure risk, to give it an overall high vulnerability score to climate change. This result should also be considered with the fact that, like many rockfishes, periods of low productivity is not unusual to `r spp` and their extended longevity (though admittedly this seems shorter than previously believed and should be reconsidered) has historically allowed them to wait for advantageous productivity periods. Stressors such as habitat degradation and climate change could bring significant challenges to population sustainability. Regardless, no environmental or ecosystem data are directly incorporated into the stock assessment model.
