# Management 

## Reference Points

Reference points were calculated using the estimated fishery selectivity and removals in the most recent year of the model (2024, @tbl-ref-points). Sustainable total yields  were `r round(model_output$derived_quants[model_output$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ reference harvest rate. The spawning output equivalent to 40 percent of the unfished spawning output ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_SPR', 'Value'], 2)` **millions of eggs**. 

The `r endyr + 1` spawning output relative to unfished equilibrium spawning output is above the `r spp` relative biomass target of 40 percent (Figure \ref{fig:depl}). The fishing intensity, $1-SPR$, of recent years was near or above the harvest rate limit ($SPR_{50\%}$) for most of the 1980s and 1990s. Recent years also show near target fishing levels (Table \ref{tab:timeseries} and Figure \ref{fig:1-spr}), highlighting how the sustainability of current fishing levels are very sensitive to incoming recruitment. Table \ref{tab:ReferencePoints} shows the full suite of estimated reference points for the base model and Figure \ref{fig:yield} shows the equilibrium curve based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`. Figure \ref{fig:phase} shows the time series of biomass and fishing intensity relative to reference points.

Reference points were based on the rockfish $\text{F}_{MSY\%}$ proxy ($\text{SPR}_{50\%}$), target relative biomass (40%), and estimated selectivity and catch for each fleet (Table \ref{tab:ReferencePoints}). The `r spp` population in Washington at the start of 2023 is estimated to be just above the target biomass, and fishing intensity during 2022 is estimated to be just below the fishing intensity target (Figure \ref{fig:phase}). The yield values are lower than the previous assessment for similar reference points due to updated life history estimates and estimates of the total scale of the population, despite the overall stock status being a bit higher. The proxy MSY values of management quantities are by definition more conservative compared to the estimated MSY and MSY relative to 40% of unfished spawning output because of the assumed steepness value. Sustainable total yield, removals, using the proxy $\text{SPR}_{50\%}$ is `r format(model_output[model_output$label=="Dead_Catch_SPR",2], digits = 3, scientific = FALSE, big.mark = ',')` mt. The spawning output equivalent to 40% of the unfished spawning output ($\text{SO}_{40\%}$) calculated using the SPR target ($\text{SPR}_{50\%}$) was `r format(model_output[model_output$label=="spawning_biomass_spr",2], digits = 4, scientific = FALSE, big.mark = ',')` billions of eggs. 

Recent removals since 2017 have been at or below the point estimate of potential long-term yields calculated using an $\text{SPR}_{50\%}$ reference point (Figure \ref{fig:1-spr}), leading to a  population that has continued to increase over recent years with the assistance of above average recruitment between 2003-2014, despite below average recruitment starting in 2015. The equilibrium estimates of yield relative to biomass based on a steepness value fixed at `r round(h, 2)` are provided in Figure \ref{fig:yield}, where vertical dashed lines indicate the estimate of fraction unfished at the start of `r end_year +1` (current) and the estimated management targets calculated based on the relative target biomass (B target), the SPR target, and the maximum sustainable yield (MSY). 

The 2023 spawning biomass relative to unfished equilibrium spawning biomass, based on the 2022 fishing year, is `r 100*stock.status.current`%, above the management target of 40% of unfished spawning output. The relative biomass and the ratio of the estimated SPR to the management target ($\text{SPR}_{50\%}$) across all model years are shown in Figure \ref{fig:phase} where warmer colors (red) represent early years and colder colors (blue) represent recent years.  There have been periods where the stock status has decreased below the target and limit relative biomass, and fishing intensity has been higher than the target fishing intensity based on $\text{SPR}_{50\%}$.

## Management performance

`r Spp` removals have been below the equivalent Annual Catch Limit (ACL) over the recent decade (Table \ref{tab:manage}). The ACL declined in 2017 relative to earlier years based on the 2015 assessment of `r spp` [@cope_assessments_2016]. In the last ten years, catches peaked in 2016 at 369 mt. Since then catches have declined to a recent low of 130 mt in 2020 with the catches in the final two model years remaining low with 197 mt in 2021 and 166 mt in 2022. The OFL has not been exceeded in any year over the past 10 years.


## Harvest Projections and Decision Tables

The `r spp` assessment is being considered as a category 1 assessment with a $P^*$ = 0.45, $\sigma$ = 0.50, and a time-varying buffer applied to set the ABC below the OFL. These multipliers are also combined with the rockfish MSY proxy of SPR\textsubscript{50} and the 40-10 harvest control rule to calculate OFLs and ACLs. A twelve-year (2023-2034) projection of the reference model using these specifications along with input removals for 2023 and 2024 provided by the Groundfish Management Team (Katie Pierson, ODFW, pers. comm.) is provided in Table \ref{tab:project}. 

Uncertainty in management quantities for the reference model was characterized by exploring various model specifications in a decision table, with the desire for states of nature to represent uncertainty in both scale and relative stock status  Initial explorations considering alternative specifications of natural mortality. This was based on using the estimated $M$ scenario as a low state of nature and applying the sex-specific $M$ values from the 2023 Oregon model as the high state of nature. These produced wide states of nature (Figure \ref{fig:stateofnature_SO} and Figure \ref{fig:stateofnature_depl}). Discussion with the STAR panel led to defining two other states of nature based on the reference model uncertainty in ending spawning output. Low and high states of nature were determined by applying an initial recruitment ($lnR_0$) value that lead to current spawning output values equivalent to the 12.5% and 87.5% percentile values from the current spawning output distribution (Figure \ref{fig:stateofnature_SO} and Figure \ref{fig:stateofnature_depl}) that are not as widely spread as the initial states of nature, but are constructed from the current model specifications. The resultant decision table (Table \ref{tab:dec-tab}) was built around the initial $lnR_0$ states of nature approach. The catch rows assume P* values of 0.45 and 0.4, then a constant catch using the yield at FSPR=0.5.


## Evaluation of Scientific Uncertainty

#The model-estimated uncertainty around the `r end_year+1` spawning biomass was $\sigma$ = `r round(100,2)` and the uncertainty around the OFL was $\sigma$ = `r round(model_output$uncertainty[model_output$label=="catch_ofl"][1], 2)`. This is likely underestimate of overall uncertainty because of the necessity to fix some life history parameters such as natural mortality and steepness, as well as a lack of explicit incorporation of model structural uncertainty. The alternative states of nature used to bracket uncertainty in the decision table assist with encapsulating model structure uncertainty.

## Research and Data Needs

This section briefly highlights progress on research and data needs identified in the most recent (2015) `r spp` assessment, and then provides recommendations for future research.

Research and data needs identified in the last assessment (italics) are listed here followed by a brief response for each.
