# Tables 

```{r}
#| label: management_summary
#| warning: false
#| echo: false
#| tbl-cap: "Major management actions since 2000 that have impacted the management of the Rougheye/Blackspotted complex."

management_summary <- read.csv(here::here("Document/report/rda_files/management-summary.csv"))
management_summary |> 
   gt::gt() |>
   #gt::cols_label(
   # `Year` = "Year",
   # `Management_action` = "Management Action"
  #) |>
   gt::tab_options(
     table.font.size = 12,
     latex.use_longtable = TRUE
   ) |>
   gt::as_latex()

```

\pagebreak

```{r}
#| label: tbl-landings
#| warning: false
#| echo: false
#| tbl-cap: "Landings in metric tons (mt) by year for each fleet."

landings <- model_output[["catch"]] |>
  tibble::as_tibble() |>
   dplyr::select(Fleet_Name, Yr, ret_bio) |>
   dplyr::group_by(Yr) |>
   dplyr::mutate(
     ret_bio = round(ret_bio, 0),
     `Total (mt)` = sum(ret_bio)
   ) |>
   tidyr::pivot_wider(
     names_from = Fleet_Name,
     values_from = ret_bio
   ) |>
   dplyr::rename(
     Year = Yr,
     `Trawl (mt)` = BOTTOM_TRAWL,
     `Trawl Discard (mt)` = BOTTOM_TRAWL_DISCARD,
     `Non-trawl (mt)` = NON_TRAWL,
     `Non-trawl discard (mt)` = NON_TRAWL_DISCARD,
      `Midwater trawl (mt)` = MIDWATER_TRAWL,
     `At-sea-Hake (mt)` = AT_SEA_HAKE
   ) |>
   dplyr::ungroup()
kableExtra::kable(
  landings, 
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Landings in metric tons (mt) by year for each fleet.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8)
#knitr::kable(landings)
    
```

\pagebreak


```{r, results = "asis"}
#| label: tbl-management
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) recent_management_cap 
#| tbl-pos: H

recent_management_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:5,
    decimals = 0
  ) |>
  gt::tab_options(
    table.font.size = 12 
  ) |>
  gt::cols_align(
    align = "center"
  ) |>
  gt::cols_width(
    tidyselect::everything() ~ px(75)
  ) |>
  gt::as_latex()

```

\pagebreak


#```{r, results = "asis"}
##| label: tbl-area-spex
##| warning: false
##| echo: false
##| tbl-cap: "Adopted coastwide OFL (mt) and ABC (mt) values and the area-based ACL (mt) north and south of 36 N. latitude by year."
##| tbl-pos: H

#area_management_table |>
#  gt::gt() |>
#  gt::fmt_number(
#    columns = c(2:5),
#    decimals = 0
#  ) |>
#  gt::tab_options(
#    table.font.size = 12,
#    latex.use_longtable = TRUE 
#  ) |>
#  gt::as_latex()

#```

\pagebreak


```{r}
#| label: tbl-model-config
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) config_cap

config_table |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```


```{r}
#| label: tbl-n-param
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) parcount_cap

parcount_table |>
  gt::gt() |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

 {{< pagebreak >}} 
 
::: {.landscape}

```{r}
#| label: tbl-param
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) par_cap 
#| tbl-pos: H

par_table |>
  flextable::flextable() |>
  flextable::fontsize(size = 8) |>
  flextable::width(
    j = c(1, 2, 3, 4, 5, 6, 7),
    width = c(2, 0.5, 0.5, 1.5, 0.5, 0.5, 2.5)
  ) 

```

::: 

 {{< pagebreak >}} 
 
 
```{r}
#| label: tbl-likes
#| warning: false
#| echo: false
#| tbl-cap: "Likelihood components by source."

table <- dplyr::bind_cols(
  data.frame(Label = gsub("_", " ", rownames(model_output$likelihoods_used) )), 
  data.frame(Total = model_output$likelihoods_used[,1])
)
table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2,
    decimals = 1
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE
  ) |>
  gt::as_latex()

```

 {{< pagebreak >}} 


```{r, results = "asis"}
#| label: tbl-ref-points
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) reference_points_cap 
#| tbl-pos: H

reference_points_table |>
  gt::gt() |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(1:4, 7, 10, 12, 15, 17, 20),
    decimals = 0
  ) |>
  gt::fmt_number(
    columns = 2:4,
    rows = c(5, 8, 9, 13:14, 18:19),
    decimals = 3
  ) |>
  gt::tab_options(
    table.font.size = 12,
    latex.use_longtable = TRUE 
  ) |>  
  gt::tab_style(
    style = list(
      gt::cell_text(style = "italic")
    ),
    locations = gt::cells_body(
      columns = "Reference Point",
      rows = tidyselect::starts_with("Reference")
    )
  ) |>
  gt::sub_missing(
    columns = tidyselect::everything(),
    missing_text = "---"
  ) |>
  gt::as_latex()

```


\pagebreak


```{r, results = "asis"}
#| label: tbl-ts
#| warning: false
#| echo: false
#| eval: !expr eval_tables 
#| tbl-cap: !expr if(eval_tables) time_series_cap 
#| tbl-pos: H

time_series_table |>
kableExtra::kable(
  format = "latex", 
  longtable = TRUE,
  booktabs = TRUE,
  caption = "Time series of population estimates from the base model.",
  linesep = "") |>
  kableExtra::kable_styling(
    latex_options = "repeat_header",
    font_size = 8) |>
  kableExtra::column_spec(
    column = 1:9,
    width = "0.5in"
  )

```


\pagebreak


<---- sensitivities --->


```{r}
#| label: tbl-sensitivities-like-indices
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (indices)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
indices <- read.csv(here::here("Document","report", "Sensis", "output", "indices_table.csv"))

names(indices) <- c("Label","Base","- Triennial","- AK Slope","-NW slope","- WCGBTS","No indices")

table_sens(indices)

cat("\n\\end{landscape}\n") 
```

\pagebreak

```{r}
#| label: tbl-sensitivities-like-lens1
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (length compositions by fleet)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
lens1 <- read.csv(here::here("Document","report", "Sensis", "output", "length_comps_fleet_table.csv"))

names(lens1) <- c("Label","Base","- bottom trawl","- non-trawl","- mid-water trawl","- ASHOP","- Triennial","- AK slope","- NW slope","- WCGBTS")

table_sens(lens1)

cat("\n\\end{landscape}\n") 

```

\pagebreak


```{r}
#| label: tbl-sensitivities-like-lens2
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (length compositions by source)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
lens2 <- read.csv(here::here("Document","report", "Sensis", "output", "length_comps_all_table.csv"))

names(lens2) <- c("Label","Base","- fishery","- survey","no lengths")

table_sens(lens2)

cat("\n\\end{landscape}\n") 

```

\pagebreak


```{r}
#| label: tbl-sensitivities-like-age
#| echo: false
#| message: false
#| warning: false
#| results: "asis"
#| tbl-cap: "Base model sensitivity to the removal of data sources (age compositions by fleet)."

cat("\\begin{landscape}\n")

source(here::here("Rcode/table_sens.R"))
ages <- read.csv(here::here("Document","report", "Sensis", "output", "age_comps_table.csv"))

names(ages) <- c("Label","Base","- bottom trawl","- non-trawl","- mid-water trawl","- ASHOP","- WGCBTS","- fishery","no ages")

table_sens(ages)

cat("\n\\end{landscape}\n") 

```

\pagebreak

#::: {.landscape}

#```{r, results = "asis"}
##| label: tbl-projections
##| warning: false
##| echo: false
##| eval: !expr eval_tables 
##| tbl-cap: !expr if(eval_tables) projections_cap 
##| tbl-pos: H

#projections_table |>
#  gt::gt() |>
#  gt::fmt_number(
#    columns = c(2:5, 7:9),
#    decimals = 0
#  ) |>
#  gt::fmt_number(
#    columns = c(6, 10),
#    decimals = 3
#  ) |>
#  gt::tab_options(
#    table.font.size = 12,
#    latex.use_longtable = TRUE 
#  ) |>
#  gt::sub_missing(
#    columns = tidyselect::everything(),
#    missing_text = "---"
#  ) |>
#  gt::cols_align(
 #   align = "center"
 # ) |>
 # gt::cols_width(
 #   tidyselect::everything() ~ px(75)
 # ) |>
 # gt::as_latex()

#```

#:::

#\pagebreak