---
title: 'Status of the Rougheye and Blackspotted Rockfishes stock off the U.S. West Coast in 2025'
author:
  - name: 'Jason M. Cope'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
  - name: 'Vladlena Gertseva'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
  - name: 'NA'
    affiliations: NO AFFILIATION
  - name: 'NA'
    affiliations: NO AFFILIATION
  - name: 'NA'
    affiliations: NO AFFILIATION
date: today
lang: en 
keep-tex: true 
cover: 
pdf-engine: lualatex
format: 
  pdf: 
    documentclass: scrartcl
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
    toc: true
    lof: true
    lot: true
    titlepage-geometry: 
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
output-file: 'Rougheye_and_Blackspotted_Rockfishes_SAR_2025' 
params:
   office: 'NWFSC'
   species: 'Rougheye and Blackspotted Rockfishes'
   spp_latin: 'Sebastes aleutianus'
   region: 'U.S. West Coast'
---
```{r} 
#| label: 'output_and_quantities'
#| echo: false 
#| warning: false 
#| eval: true 
output <- utils::read.csv('C:/Users/Jason.Cope/Documents/Github/REBS-2025/Document/reye_blkspt_convert_output.csv') 
# Call reference points and quantities below 
# start_year <- min(output$year) 
# end_year <- '2025' 
# Fend <- output$estimate[output$label == 'fishing_mortality' & output$year == year] 
# Ftarg 
# F_Ftarg 
# Bend 
# Btarg 
# tot_catch
# sbtarg
# M 
# Bmsy 
# SBmsy 
# steep 
# R0
# fSB 

``` 

{{< pagebreak >}} 

Please cite this publication as 

Cope, J.M., V. Gertseva, F. Caltabellotta, C. Rosemond, A.D. Whitman. 2025. Status of the Rougheye and Blackspotted Rockfishes stock off the U.S. West Coast in 2025. NOAA Fisheries Science Center, Seattle, WA. 

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'executive_summary'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('01_executive_summary.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'introduction'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('02_introduction.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('03_data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-configuration'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04a_assessment-configuration.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-results'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04b_assessment-results.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-sensitivity'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04c_assessment-sensitivity.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-benchmarks'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04d_assessment-benchmarks.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'assessment-projections'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('04e_assessment-projections.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'discussion'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('05_discussion.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'acknowledgments'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('06_acknowledgments.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'references'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('07_references.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'tables'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('08_tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'figures'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('09_figures.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'notes'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('10_notes.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('11_appendix.qmd', quiet = TRUE)
cat(a, sep = '\n')
```
